# Generated by Django 3.1.2 on 2021-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211026_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='packagePrice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
