# Generated by Django 3.1.2 on 2021-10-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
