# Generated by Django 3.1.2 on 2021-10-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211027_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sevice_desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
