# Generated by Django 3.1.2 on 2021-10-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_addes',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
