# Generated by Django 3.1.2 on 2021-10-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message_date_addes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_addes',
            new_name='date_added',
        ),
    ]
