# Generated by Django 3.1.2 on 2021-10-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211027_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_class_name',
            field=models.CharField(blank=True, default='bx bxl-dribbble', max_length=255, null=True),
        ),
    ]
