# Generated by Django 3.1.2 on 2021-10-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tourpackage_day_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayaction',
            name='day_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
