# Generated by Django 3.2.8 on 2021-11-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211030_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
