# Generated by Django 3.2.8 on 2021-11-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_service_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(blank=True, max_length=255, null=True)),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slide_descr', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
