# Generated by Django 3.2.8 on 2021-11-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
