# Generated by Django 3.2.8 on 2021-11-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hotel_hotelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('destinationImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('slogan', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
