# Generated by Django 3.2.8 on 2021-11-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('VOLCANOES', 'VOLCANOES'), ('NATIONAL PARKS', 'NATIONAL PARKS'), ('LAKES & MUSEUMS', 'LAKES & MUSEUMS')], default='VOLCANOES', max_length=15),
        ),
    ]
