# Generated by Django 3.2.8 on 2021-12-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_destination_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
        migrations.AlterField(
            model_name='destination',
            name='slogan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sevice_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide_descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='package_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
