# Generated by Django 3.2.8 on 2021-12-15 19:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20211201_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
